#:schema ./schema.json

# Default model to use for AI completions
default_model = "gpt-4o-mini"

# === OpenAI Configuration ===
# OpenAI API key - replace with your actual key
openai_api_key = "your-openai-api-key"
# Optional: Custom OpenAI API URL (if using a proxy or compatible API)
# openai_api_url = "https://custom-openai-endpoint.com/v1"

# === Gemini Configuration ===

gemini_api_key = "your-gemini-api-key"
# gemini_api_url = "https://generativelanguage.googleapis.com"

# === Anthropic Configuration ===
# Anthropic API key for Claude models
# anthropic_api_key = "your-anthropic-api-key"

# === Groq Configuration ===
# Groq API key for faster inference
# groq_api_key = "your-groq-api-key"
# groq_api_url = "https://api.groq.com/openai/v1"

# === Mistral Configuration ===
# Mistral API key
# mistral_api_key = "your-mistral-api-key"
# mistral_api_url = "https://api.mistral.ai/v1"

# === Ollama Configuration ===
# Ollama host for local models (default: http://localhost:11434)
# ollama_host = "http://localhost:11434"

# === Blockchain Tools ===
# Etherscan API key for fetching contract ABIs
etherscan_api_key = "your-etherscan-api-key"

# === Custom Commands ===
# Optional: Configure custom commands
[commands]
 # [commands.explain]
 #  command = "explain"
 #  prompt = "Explain the following smart contract code in plain English, highlighting key functions, permissions, and security patterns:"
 #  require_stdin = true

  # [commands.generate]
  # command = "generate"
  # prompt = "Generate a secure Solidity smart contract based on these requirements:"
  # require_stdin = true
